//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "atlas_schema_revisions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub version: String,
    pub description: String,
    pub r#type: u64,
    pub applied: i64,
    pub total: i64,
    pub executed_at: Option<DateTimeUtc>,
    pub execution_time: i64,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")", nullable)]
    pub error: Option<String>,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")", nullable)]
    pub error_stmt: Option<String>,
    pub hash: String,
    pub partial_hashes: Option<Json>,
    pub operator_version: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
