//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub mod prelude;

pub mod announce;
pub mod atlas_schema_revisions;
pub mod banner;
pub mod banner_kind;
pub mod dict;
pub mod dict_item;
pub mod guide;
pub mod question;
pub mod sys_api;
pub mod sys_api_group;
pub mod sys_config;
pub mod sys_log_login;
pub mod sys_menu;
pub mod sys_menu_api;
pub mod sys_org;
pub mod sys_perm;
pub mod sys_post;
pub mod sys_role;
pub mod sys_role_user;
pub mod sys_user;
pub mod sys_user_org;
pub mod sys_user_post;
