//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::announce::Entity as Announce;
pub use super::atlas_schema_revisions::Entity as AtlasSchemaRevisions;
pub use super::banner::Entity as Banner;
pub use super::banner_kind::Entity as BannerKind;
pub use super::dict::Entity as Dict;
pub use super::dict_item::Entity as DictItem;
pub use super::guide::Entity as Guide;
pub use super::log_login::Entity as LogLogin;
pub use super::question::Entity as Question;
pub use super::sys_api::Entity as SysApi;
pub use super::sys_resource::Entity as SysResource;
pub use super::sys_resource_api::Entity as SysResourceApi;
pub use super::sys_role::Entity as SysRole;
pub use super::sys_role_user::Entity as SysRoleUser;
pub use super::sys_user::Entity as SysUser;
