//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "sys_menu")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub pid: i64,
    pub tier: String,
    pub r#type: String,
    pub name: String,
    pub permission: String,
    pub title: String,
    pub path: String,
    pub icon: String,
    pub breadcrumb: String,
    pub component: String,
    pub remark: String,
    pub sort: u32,
    pub is_enabled: String,
    pub visible: String,
    pub is_affix: String,
    pub is_keep_alive: String,
    pub is_iframe: String,
    pub hyperlink: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
