[package]
name = "entity"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
sea-orm.workspace = true
serde.workspace = true
utoipa.workspace = true

[lints]
workspace = true
